# Generated by Django 5.2.7 on 2025-11-02 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ckan_id', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ckan_id', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('notes', models.TextField(blank=True)),
                ('theme', models.CharField(blank=True, max_length=120)),
                ('metadata_created', models.DateTimeField(blank=True, null=True)),
                ('metadata_modified', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='catalogue.organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='catalogue.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ckan_id', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('format', models.CharField(db_index=True, max_length=40)),
                ('url', models.URLField(max_length=1000)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='catalogue.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orgs', to='catalogue.source'),
        ),
    ]
